---
title: "eds212_day2_activities"
author: "Takeen Shamloo"
format: html
editor_options: 
  chunk_output_type: console
---

## Section 2: Derivatives in R

```{r}
# Loading packages ----
library(tidyverse)
library(palmerpenguins)
```

# Derivatives using R ----

```{r}
# Function f(x) = x^2 at x = 3 ----
dfDx <- D(expression(x^2), "x")

# Setting x = 3 ----
x <- 3

# Evaluate dfDx at x = 3 ----
eval(dfDx)
```


```{r}
# Function P(a) = 2(3a + 2)^4 - 5 a = 1.2 ----
dpDa <- D(expression(2 * (3 * a + 2)^4 - 5), "a")

# Setting a = 1.2 ----
a <- 1.2

# Evaluating dpDa at a = 1.2 ----
eval(dpDa)
```

# Section 3: Make another penguin plot

```{r}
# create plot for bill length vs depth ----
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("forestgreen","maroon","turquoise")) +
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       title = "Palmer penguin measurement comparison",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
```

```{r}
# create jitter plot for flipper length by species 
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  scale_color_manual(values = c("pink","green","blue")) +
  labs(x = "Species",
       y = "Flipper length (mm)",
       title = "Palmer penguin measurement comparison",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
```





